In [1]:
import numpy as np
print(np.__version__)

1.18.5


In [2]:
#how to craete numpy array
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
b=np.arange(10)
print(b)
print(type(b))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
l=list(range(1000))
%timeit [i**2 for i in l]

695 µs ± 167 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
l1=np.arange(1000)#array range
%timeit np.array(i**2 for i in l1)

5.1 µs ± 78 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
#check dimension shape and length
a=np.array([[1,2,3]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(len(a))

[[1 2 3]]
<class 'numpy.ndarray'>
2
(1, 3)
1


In [7]:
c = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
#linspace function is used to linearly spaced data
#c = np.linspace(0,1,6)

In [9]:
import numpy as np
d = np.ones((3,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
a=np.random.randint(0,20,15)
print(a)

[ 2  6 17  1 14  0  3 15  9  3 16  1  7 12 15]


In [11]:
#masking a numpy array
mask=(a%2==0)
print(mask)

[ True  True False False  True  True False False False False  True False
 False  True False]


In [12]:
print(a[mask])

[ 2  6 14  0 16 12]


In [13]:
mask=(a%2!=0)
a[mask]=-1
print(a)


[ 2  6 -1 -1 14  0 -1 -1 -1 -1 16 -1 -1 12 -1]


In [14]:
#it is possible to index array data in the form of interger index
a[[0,2,3,5,6]]=77
print(a)

[77  6 77 77 14 77 77 -1 -1 -1 16 -1 -1 12 -1]


In [15]:
a[[i for i in range(6)]]=77
print(a)
print(type(a))

[77 77 77 77 77 77 77 -1 -1 -1 16 -1 -1 12 -1]
<class 'numpy.ndarray'>


In [16]:
a[[i for i in range(4)]]=111
print(a)

[111 111 111 111  77  77  77  -1  -1  -1  16  -1  -1  12  -1]


In [17]:
#operations of numpy array
a=np.array([1,2,3,4,5])
print(a+1)

[2 3 4 5 6]


In [18]:
print(a**2)

[ 1  4  9 16 25]


In [19]:
a=np.ones((3,3),dtype='int') * 3;

In [20]:
b=np.diag([1,2,3])
print(a+b)

[[4 3 3]
 [3 5 3]
 [3 3 6]]


In [21]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
a==b
np.array_equal(a,b)

True

In [22]:
a=np.array([1,0,1,0], dtype='bool')
a=np.array([1,0,1,0], dtype='bool')


In [23]:
#mathematical operations
a=np.arange(4)
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [24]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [25]:
x = np.array([[1,2], [3,4]])
print(x);

[[1 2]
 [3 4]]


In [26]:
x.sum()

10

In [27]:
x.sum(axis=0)#note 0 refers for column majaor order and 1 refers row major order 
#by default mode is column major order

array([4, 6])

In [28]:
a=np.array([1,2,3,4])
a.mean()


2.5

In [29]:
np.median(a)

2.5

In [30]:
a.std()

1.118033988749895

In [31]:
data=np.loadtxt('populations.txt')

In [32]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [33]:
data[:,0]

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [34]:
#current working dir
pwd

NameError: name 'pwd' is not defined

In [ ]:
year, hares, lynxes, carrots=data.T
print(year)

In [ ]:
population=data[:,1:]
np.argmax(population,axis=1)

In [ ]:
#Boadcasting
a=np.array([[0,1,2]])
b=np.array([[0],[1],[2]])
print(a+b)
print(a-b)
print(a*b)

In [35]:
a=np.tile(np.arange(3),(3,3))
a

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [ ]:
a=np.array([[1,2,3],[9,10,11]])
b=np.array([[6,7],[11,8]])
c=np.append(a,b,axis=1)
print(c)

In [ ]:
#new axis
#ravel function
#flatting data
a= np.array([[1,2],[3,4]])
print(a)
a=a[:,np.newaxis]
print(a.shape)
print(a.ndim)
print(a)

In [ ]:

a=np.array(([1,2,3],[4,5,6]))
print(a.ravel())

In [ ]:
#reshapeing is opposite to flatting
a=np.array([1, 2, 3, 4,5 ,6])
print(a)
a.reshape(3,2)

In [ ]:
#resize (fill empty places zero)
a=np.arange(4)
a.resize((8,))
print(a)

In [49]:
a=np.arange(0,24,2)
a.reshape(4,3)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [50]:
a.flatten()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

# panads 

In [55]:
import pandas as pd
print(pd.__version__)

1.0.5


In [58]:
#how to create a pandas object
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [61]:
data=[1,2,3,4]
df=pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4


In [65]:
data=[['rahul',35],['Shalilendra',25]]
df=pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df)

          Name   Age
0        rahul  35.0
1  Shalilendra  25.0


In [71]:
#how to create dataframe from dictionary
data={'Name': ['rahul','vasu','neha'],'Age':[35,6,22],}
df=pd.DataFrame(data,index=['row1','row2','row3'])
print(df)

       Name  Age
row1  rahul   35
row2   vasu    6
row3   neha   22


In [87]:
#datasets
df=pd.read_csv('downloads/nyc_weather.csv')
df.head(15)

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0                10           8.0               0           5    NaN   
1                10           7.0               0           3    NaN   
2                10           8.0               0           1    NaN   
3                10           9.0               0           3    NaN   
4                10           5.0               0           0    NaN   
5                10           4.0               0           0    NaN   
6                10           2.0               0           3    NaN   
7                10           4.0               0           8    NaN   
8                 9           8.0               T           8   Rain   
9                 4           NaN             1.8           7   Rain   
10               10           NaN               0           1    NaN   
11               10           6.0               T           4    NaN   
12               10          10.0               0           0    NaN   
13               10           5.0               T           7    NaN   
14                9           5.0               T           2    NaN   

    WindDirDegrees  
0              281  
1              275  
2              277  
3              345  
4              333  
5              259  
6              293  
7               79  
8               76  
9              109  
10             289  
11             235  
12             284  
13             266  
14             101

In [98]:
df1=df[['Temperature','EST']][(df['Events']=='Rain') & (df['Temperature'])==(df['Temperature'].max())]
df1
#df2=df1[['Temperature','EST']][df1['Temperature'==df1['Tempetature'].max()]]

Empty DataFrame
Columns: [Temperature, EST]
Index: []

In [96]:
df1=df[['Temperature','EST']][(df['Events']=='Rain')]
df1

Temperature        EST
8            44   1/9/2016
9            50  1/10/2016
15           47  1/16/2016
26           41  1/27/2016

In [105]:
df[1:16]

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
1                10           7.0               0           3    NaN   
2                10           8.0               0           1    NaN   
3                10           9.0               0           3    NaN   
4                10           5.0               0           0    NaN   
5                10           4.0               0           0    NaN   
6                10           2.0               0           3    NaN   
7                10           4.0               0           8    NaN   
8                 9           8.0               T           8   Rain   
9                 4           NaN             1.8           7   Rain   
10               10           NaN               0           1    NaN   
11               10           6.0               T           4    NaN   
12               10          10.0               0           0    NaN   
13               10           5.0               T           7    NaN   
14                9           5.0               T           2    NaN   
15                8           7.0            0.24           7   Rain   

    WindDirDegrees  
1              275  
2              277  
3              345  
4              333  
5              259  
6              293  
7               79  
8               76  
9              109  
10             289  
11             235  
12             284  
13             266  
14             101  
15             340

In [107]:
df.describe()

Temperature   DewPoint   Humidity  Sea Level PressureIn  \
count    31.000000  31.000000  31.000000             31.000000   
mean     34.677419  17.838710  51.677419             29.992903   
std       7.639315  11.378626  11.634395              0.237237   
min      20.000000  -3.000000  33.000000             29.520000   
25%      29.000000  10.000000  44.500000             29.855000   
50%      35.000000  18.000000  50.000000             30.010000   
75%      39.500000  23.000000  55.000000             30.140000   
max      50.000000  46.000000  78.000000             30.570000   

       VisibilityMiles  WindSpeedMPH  CloudCover  WindDirDegrees  
count        31.000000     28.000000   31.000000       31.000000  
mean          9.193548      6.892857    3.129032      247.129032  
std           1.939405      2.871821    2.629853       92.308086  
min           1.000000      2.000000    0.000000       34.000000  
25%           9.000000      5.000000    1.000000      238.000000  
50%          10.000000      6.500000    3.000000      281.000000  
75%          10.000000      8.000000    4.500000      300.000000  
max          10.000000     16.000000    8.000000      345.000000

In [115]:
df1={'Name': ['richa','prachi','neha'],'Age':[20,21,22],}
df1

{'Name': ['richa', 'prachi', 'neha'], 'Age': [20, 21, 22]}

In [117]:
df2 = {"a": [1, 2, 3, 4], "b": [2, 4, 6, 8]}
df2 = pd. DataFrame(d)
df

a  b
0  1  2
1  2  4
2  3  6
3  4  8

In [127]:
sum = df["a"] + df["b"]
df["col3"] = sum
df

a  b  col3   c
0  1  2     3   3
1  2  4     6   6
2  3  6     9   9
3  4  8    12  12